/*
Created		4/8/2024
Modified		4/15/2024
Project		
Model		
Company		
Author		
Version		
Database		mySQL 5 
*/


DROP DATABASE IF EXISTS BD_CLASES_CARLOS_HERNANDEZ;
CREATE DATABASE BD_CLASES_CARLOS_HERNANDEZ;
USE BD_CLASES_CARLOS_HERNANDEZ;


Create table ALUMNOS (
	CODIGO_ALUMNO Char(7) NOT NULL COMMENT 'ALU-001',
	CONVOCATORIAS_ALUMNO Integer(1) NOT NULL,
	CODIGO_MODULO Char(7) NOT NULL,
	NOMBRE_ALUMNO Varchar(15) NOT NULL,
	APELLIDO1_ALUMNO Varchar(15) NOT NULL,
	APELLIDO2_ALUMNO Varchar(15) NOT NULL,
	FECHA_NACIMIENTO_ALUMNO Date NOT NULL,
 Primary Key (CODIGO_ALUMNO,CONVOCATORIAS_ALUMNO,CODIGO_MODULO)) ENGINE = InnoDB;

Create table PROFESORES (
	CODIGO_PROFESOR Char(7) NOT NULL COMMENT 'INF-001',
	NOMBRE_PROFESOR Varchar(15) NOT NULL,
	APELLIDO1_PROFESOR Varchar(15) NOT NULL,
	APELLIDO2_PROFESOR Varchar(15),
	FECHA_NACIMIENTO_PROFESOR Date NOT NULL,
 Primary Key (CODIGO_PROFESOR)) ENGINE = InnoDB;

Create table MODULOS (
	CODIGO_MODULO Char(7) NOT NULL,
	NOMBRE_MODULO Varchar(10) NOT NULL,
	HORAS_SEMANALES_MODULO Integer(2) NOT NULL,
	ALUMNOS_MATRICULADOS_MODULO Integer(2) NOT NULL,
 Primary Key (CODIGO_MODULO)) ENGINE = InnoDB;

Create table CALIFICACIONES (
	CODIGO_ALUMNO Char(7) NOT NULL,
	CONVOCATORIAS_ALUMNO Integer(1) NOT NULL,
	CODIGO_MODULO Char(7) NOT NULL,
	CODIGO_PROFESOR Char(7) NOT NULL,
	NOTA_1_EVALUACION Integer(2) NOT NULL,
	NOTA_2_EVALUACION Integer(2) NOT NULL,
	NOTA_ORDINARIA Integer(2) NOT NULL,
	NOTA_EXTRAORDINARIA Char(2) NOT NULL,
 Primary Key (CODIGO_ALUMNO,CONVOCATORIAS_ALUMNO,CODIGO_MODULO,CODIGO_PROFESOR)) ENGINE = InnoDB;

Create table CURSOS (
	CODIGO_CURSO Char(7) NOT NULL,
	ANHO_CURSO Date NOT NULL,
	PLAZAS_CURSO Char(2) NOT NULL,
 Primary Key (CODIGO_CURSO,ANHO_CURSO)) ENGINE = InnoDB;

Create table CATALOGO_CURSOS (
	CODIGO_CURSO Char(7) NOT NULL,
	CODIGO_MODULO Char(7) NOT NULL,
 Primary Key (CODIGO_CURSO,CODIGO_MODULO)) ENGINE = InnoDB;


