/*
Created		4/8/2024
Modified		4/15/2024
Project		
Model		
Company		
Author		
Version		
Database		mySQL 5 
*/


drop table IF EXISTS CATALOGO_ANHO_QUE_VIENE;
drop table IF EXISTS CURSOS;
drop table IF EXISTS CALIFICACIONES;
drop table IF EXISTS MODULOS;
drop table IF EXISTS PROFESORES;
drop table IF EXISTS ALUMNOS;


Create table ALUMNOS (
	CODIGO_ALUMNO Char(7) NOT NULL COMMENT 'ALU-001',
	CONVOCATORIAS_ALUMNO Char(1) NOT NULL,
	CODIGO_MODULO Char(7) NOT NULL,
	NOMBRE_ALUMNO Varchar(15) NOT NULL,
	APELLIDO1_ALUMNO Varchar(15) NOT NULL,
	APELLIDO2_ALUMNO Varchar(15) NOT NULL,
	FECHA_NACIMIENTO_ALUMNO Date NOT NULL,
 Primary Key (CODIGO_ALUMNO,CONVOCATORIAS_ALUMNO,CODIGO_MODULO)) ENGINE = InnoDB;

Create table PROFESORES (
	CODIGO_PROFESOR Char(7) NOT NULL COMMENT 'INF-001
',
	NOMBRE_PROFESOR Varchar(15) NOT NULL,
	APELLIDO1_PROFESOR Varchar(15) NOT NULL,
	APELLIDO2_PROFESOR Varchar(15),
	FECHA_NACIMIENTO_PROFESOR Date NOT NULL,
 Primary Key (CODIGO_PROFESOR)) ENGINE = InnoDB;

Create table MODULOS (
	CODIGO_MODULO Char(7) NOT NULL,
	NOMBRE_MODULO Varchar(10) NOT NULL,
	HORAS_SEMANALES_MODULO Char(3) NOT NULL,
	ALUMNOS_MATRICULADOS_MODULO Char(3) NOT NULL,
 Primary Key (CODIGO_MODULO)) ENGINE = InnoDB;

Create table CALIFICACIONES (
	CODIGO_ALUMNO Char(7) NOT NULL,
	CONVOCATORIAS_ALUMNO Char(1) NOT NULL,
	CODIGO_MODULO Char(7) NOT NULL,
	CODIGO_PROFESOR Char(7) NOT NULL,
	NOTA_1_EVALUACION Char(2) NOT NULL,
	NOTA_2_EVALUACION Char(2) NOT NULL,
	NOTA_ORDINARIA Char(2) NOT NULL,
	NOTA_EXTRAORDINARIA Char(2) NOT NULL,
 Primary Key (CODIGO_ALUMNO,CONVOCATORIAS_ALUMNO,CODIGO_MODULO,CODIGO_PROFESOR)) ENGINE = InnoDB;

Create table CURSOS (
	CODIGO_CURSO Char(20) NOT NULL,
	ANHO_CURSO Char(20) NOT NULL,
	PLAZAS_CURSO Char(20) NOT NULL,
 Primary Key (CODIGO_CURSO)) ENGINE = InnoDB;

Create table CATALOGO_ANHO_QUE_VIENE (
	CODIGO_CURSO Char(20) NOT NULL,
	CODIGO_MODULO Char(7) NOT NULL,
 Primary Key (CODIGO_CURSO,CODIGO_MODULO)) ENGINE = InnoDB;


